version: '3.5'

services:

  fizzbuzz:
    build:
      context: ./
    environment:
      SERVER_PORT: 8080
      LOG_LEVEL: debug
      DB_USERNAME: username
      DB_PASSWORD: password
#     CORS_ALLOWED_ORIGINS:
#     CORS_ALLOWED_METHODS:
    ports:
      - "8080:8080"
