version: '3.5'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  fizzbuzz:
    build:
      context: ./
    environment:
      SERVER_PORT: 8080
      LOG_LEVEL: debug
      BD_URL: jdbc:postgresql://postgres:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
#     CORS_ALLOWED_ORIGINS:
#     CORS_ALLOWED_METHODS:
    ports:
      - "8080:8080"
    depends_on:
      - postgres
