server:
  port: ${SERVER_PORT:8080}

application:
  versionApi: 1
  cors:
    allowedOrigins: ${CORS_ALLOWED_ORIGINS:}
    allowedMethods: ${CORS_ALLOWED_METHODS:}

logging:
  level:
    com:
      leboncoin: ${LOG_LEVEL:debug}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
