server:
  port: ${SERVER_PORT:8080}

application:
  versionApi: 1
  cors:
    allowedOrigins: ${CORS_ALLOWED_ORIGINS:}
    allowedMethods: ${CORS_ALLOWED_METHODS:}

logging:
  level:
    com:
      boubou: ${LOG_LEVEL:debug}

spring:
  datasource:
    url: ${BD_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:fizzbyzz_user}
    password: ${DB_PASSWORD:fizzbyzz_password}

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
